version: "3.8"

services:
  db:
    build:
      context: ./market
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5003
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fix-me
    ports:
      - 5003:5432

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: unless-stopped
    links:
      - db
